// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entity/chat.dart';
import 'entity/debug.dart';
import 'entity/knowledge.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2563098524687269382),
    name: 'Knowledge',
    lastPropertyId: const obx_int.IdUid(3, 3616058206899074122),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7454449457066490399),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3052910870772141662),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3616058206899074122),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(3, 5343879432585865271),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 7166730782826892657),
    name: 'Debug',
    lastPropertyId: const obx_int.IdUid(3, 2658302180526032102),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1362100939994103846),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 796489678724245394),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2658302180526032102),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(4, 500852027354353933),
        hnswParams: obx_int.ModelHnswParams(dimensions: 3, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 6031908967236263197),
    name: 'Chat',
    lastPropertyId: const obx_int.IdUid(6, 8766794078658767422),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5434325169624088095),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 644663752843412903),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4764685395943291104),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1531990624908601514),
        name: 'prompt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6845007198290842396),
        name: 'references',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8766794078658767422),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(6, 6031908967236263197),
    lastIndexId: const obx_int.IdUid(4, 500852027354353933),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      2473982829664018892,
      5980520435912860748,
      4928971987271453225,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      853057308695734837,
      2285087313363447712,
      8920058212212264789,
      4420975305487955315,
      1426900679850647831,
      4961765487799980260,
      4765647224588334242,
      8823602343662498657,
      6871824716491186039,
      6366584080122099278,
      6825210242188910810,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Knowledge: obx_int.EntityDefinition<Knowledge>(
      model: _entities[0],
      toOneRelations: (Knowledge object) => [],
      toManyRelations: (Knowledge object) => {},
      getId: (Knowledge object) => object.id,
      setId: (Knowledge object, int id) {
        object.id = id;
      },
      objectToFB: (Knowledge object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final object = Knowledge(
          id: idParam,
          text: textParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    Debug: obx_int.EntityDefinition<Debug>(
      model: _entities[1],
      toOneRelations: (Debug object) => [],
      toManyRelations: (Debug object) => {},
      getId: (Debug object) => object.id,
      setId: (Debug object, int id) {
        object.id = id;
      },
      objectToFB: (Debug object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final object = Debug(
          id: idParam,
          text: textParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    Chat: obx_int.EntityDefinition<Chat>(
      model: _entities[2],
      toOneRelations: (Chat object) => [],
      toManyRelations: (Chat object) => {},
      getId: (Chat object) => object.id,
      setId: (Chat object, int id) {
        object.id = id;
      },
      objectToFB: (Chat object, fb.Builder fbb) {
        final messageOffset = fbb.writeString(object.message);
        final roleOffset = fbb.writeString(object.role);
        final promptOffset = object.prompt == null
            ? null
            : fbb.writeString(object.prompt!);
        final referencesOffset = fbb.writeList(
          object.references.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageOffset);
        fbb.addOffset(2, roleOffset);
        fbb.addOffset(3, promptOffset);
        fbb.addOffset(4, referencesOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final promptParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final referencesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 12, []);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final object = Chat(
          id: idParam,
          message: messageParam,
          role: roleParam,
          prompt: promptParam,
          references: referencesParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Knowledge] entity fields to define ObjectBox queries.
class Knowledge_ {
  /// See [Knowledge.id].
  static final id = obx.QueryIntegerProperty<Knowledge>(
    _entities[0].properties[0],
  );

  /// See [Knowledge.text].
  static final text = obx.QueryStringProperty<Knowledge>(
    _entities[0].properties[1],
  );

  /// See [Knowledge.embedding].
  static final embedding = obx.QueryHnswProperty<Knowledge>(
    _entities[0].properties[2],
  );
}

/// [Debug] entity fields to define ObjectBox queries.
class Debug_ {
  /// See [Debug.id].
  static final id = obx.QueryIntegerProperty<Debug>(_entities[1].properties[0]);

  /// See [Debug.text].
  static final text = obx.QueryStringProperty<Debug>(
    _entities[1].properties[1],
  );

  /// See [Debug.embedding].
  static final embedding = obx.QueryHnswProperty<Debug>(
    _entities[1].properties[2],
  );
}

/// [Chat] entity fields to define ObjectBox queries.
class Chat_ {
  /// See [Chat.id].
  static final id = obx.QueryIntegerProperty<Chat>(_entities[2].properties[0]);

  /// See [Chat.message].
  static final message = obx.QueryStringProperty<Chat>(
    _entities[2].properties[1],
  );

  /// See [Chat.role].
  static final role = obx.QueryStringProperty<Chat>(_entities[2].properties[2]);

  /// See [Chat.prompt].
  static final prompt = obx.QueryStringProperty<Chat>(
    _entities[2].properties[3],
  );

  /// See [Chat.references].
  static final references = obx.QueryStringVectorProperty<Chat>(
    _entities[2].properties[4],
  );

  /// See [Chat.createdAt].
  static final createdAt = obx.QueryDateProperty<Chat>(
    _entities[2].properties[5],
  );
}
